// let a = 7;
// let b = 4;
// console.log(a + b);
// console.log(a - b);
// console.log(a * b);
// console.log(a / b);
// console.log(a % b);
// console.log(a ** b);
// console.log(a++);
// console.log(a);
// console.log(++a);
// console.log(b--);
// console.log(b);
// console.log(--b);
